AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyHonoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.handler
      Runtime: nodejs18.x
      CodeUri: .
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          PORT: '****'
          MONGODB_USER: '****'
          MONGODB_PASSWORD: '****'
          MONGODB_URL: 'clustername.****.mongodb.net'
          MONGODB_DB: '****'
